config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'generate_experiment_plates#index'
  resources :generate_experiment_plates

  # match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experiment_plate.rb
class ExperimentPlate < ApplicationRecord
  validates :plate_size, :number_of_replication, :sample, :reagent, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :experiment_plates
  validates :full_name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pagy::Backend

  def route_not_found
    render partial: 'layouts/page_not_found'
  end
end

app/controllers/generate_experiment_plates_controller.rb
class GenerateExperimentPlatesController < ApplicationController
  before_action :init_service

  def index
    @pagy, @experiment_plates = pagy(@experiment_plates_service.list)
  end

  def show
    @result = @experiment_plates_service.generate_plate
  rescue StandardError
    render partial: 'layouts/error'
  end

  def new
    @experiment_plate = @experiment_plates_service.new
  end

  def create
    @experiment_plate = @experiment_plates_service.create

    @experiment_plate.save ? (redirect_to root_url, notice: '✓ Experiment created') : (render :new, status: :unprocessable_entity)
  end

  def edit
    @experiment_plate = @experiment_plates_service.edit
  end

  def update
    @experiment_plate = @experiment_plates_service.update

    @experiment_plate == true ? (redirect_to root_url, notice: '✓ Experiment updated') : (render :new, status: :unprocessable_entity)
  end

  def destroy
    @experiment_plate = @experiment_plates_service.delete

    redirect_to root_url, notice: '✓ Experiment deleted'
  end

  private

  def init_service
    @experiment_plates_service = GenerateExperimentPlates::ExperimentPlateService.new(User.first, params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/generate_experiment_plates_helper.rb
module GenerateExperimentPlatesHelper
  def return_plate_number(plate)
    "Plate #{plate+1}"
  end

  def fill_row_wells(plate,row_number,column)
    if @result[plate][row_number][column].present?
      @result[plate][row_number][column].join(' X ')
    else
      'X'
    end
  end

  def return_columns(column_quantity)
    column_quantity + 1
  end
end

app/views/generate_experiment_plates/edit.html.erb
<br>
<div style="margin-left: 35%">
  <h2>Update Experiment Data</h2>
  <%= form_for :experiment_plate, url: generate_experiment_plate_path(@experiment_plate), method: :put do |f| %>

    <% if @experiment_plate.errors.any? %>
      <div id="error_explanation">
        <p>We have <%=@experiment_plate.errors.count%> errors before saving the experiment:</p>
        <ul style="color: darkred">
          <% @experiment_plate.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div style="margin-left: 3px">
      <div class="field">
        <br>
        <%= f.label :plate_size, "Enter plate size" %>
        <br>
        <%list = [96,384] %>
        <%= f.select(:plate_size, list) %>
      </div>

      <div class="field">
        <br>
        <%= f.label :sample, "Enter samples" %>
        <br>
        <%= f.text_field :sample, label: 'Sample' %>
        <br>
        <small style="color: grey">⚠ Split samples with space button and add new sample combination with / symbol</small>
        <br>
        <small style="color: grey">example: Blood Cells / Zinc Iron</small>
      </div>

      <div class="field">
        <br>
        <%= f.label :reagent, "Enter reagents" %>
        <br>
        <%= f.text_field :reagent, label: 'Reagent'%>
        <br>
        <small style="color: grey">⚠ Split reagents with space button and add new sample combination with / symbol</small>
        <br>
        <small style="color: grey">example: Sample-X Sample-Y / Sample-Z</small>
      </div>

      <div class="field">
        <br>
        <%= f.label :number_of_replication, "Enter number of replications" %>
        <br>
        <%= f.text_field :number_of_replication, label: 'Replicate' %>
        <br>
        <small style="color: grey">⚠ Split replicate numbers with comma (,)</small>
        <br>
        <small style="color: grey">example: 3,2</small>

      </div>
    </div>


    <br>
    <br>

    <%= link_to 'Home Page ',root_url, class: 'btn btn-dark' %>
    <%= f.button "Update", class: 'btn btn-primary', value: 'Create Experiment' %>
  <%  end %>
</div>


<style>
    #plate_size{
        font-size: 100px;
    }
</style>

app/views/generate_experiment_plates/index.html.erb
<br>
<div class="row">
  <p id="notice"><%= notice %></p>
  <div class="col">
    <%= link_to 'Create experiment', new_generate_experiment_plate_path, class: 'btn btn-outline-dark' %>
  </div>
</div>

<br />

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <h1>Experiments</h1>

        <table class="table table-striped">
          <thead>
          <tr>
            <th>Plate size</th>
            <th>Sample</th>
            <th>Reagent</th>
            <th>Replication</th>
            <th colspan="2"></th>
          </tr>
          </thead>
          <tbody>
          <% @experiment_plates.each do |experiment| %>
            <tr>
              <td class="align-middle"><%= experiment.plate_size %></td>
              <td class="align-middle"><%= experiment.sample %></td>
              <td class="align-middle"><%= experiment.reagent %>
              <td class="align-middle"><%= experiment.number_of_replication%></td>
              <td class="align-middle"><%= link_to 'Generate plate', generate_experiment_plate_path(experiment), class: 'btn btn-outline-primary' %></td>
              <td class="align-middle"><%= link_to 'Edit', edit_generate_experiment_plate_path(experiment), class: 'btn btn-warning' %></td>
              <td class="align-middle"><%= link_to 'Delete', generate_experiment_plate_path(experiment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'%></td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <div style="margin-left: 40%">
            <%== pagy_bootstrap_nav(@pagy) %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/generate_experiment_plates/new.html.erb
<br>
<div style="margin-left: 35%">
  <h2>Add Experiment Data</h2>
  <%= form_for :experiment_plate, url: generate_experiment_plates_path, method: :post do |f| %>

    <% if @experiment_plate.errors.any? %>
      <div id="error_explanation">
        <p>We have <%=@experiment_plate.errors.count%> errors before saving the experiment:</p>
        <ul style="color: darkred">
          <% @experiment_plate.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div style="margin-left: 3px">
      <div class="field">
        <br>
        <%= f.label :plate_size, "Enter plate size" %>
        <br>
        <%list = [96,384] %>
        <%= f.select(:plate_size, list) %>
      </div>

      <div class="field">
        <br>
        <%= f.label :sample, "Enter samples" %>
        <br>
        <%= f.text_field :sample, label: 'Sample' %>
        <br>
        <small style="color: grey">⚠ Split samples with space button and add new sample combination with / symbol</small>
        <br>
        <small style="color: grey">example: Blood Cells / Zinc Iron</small>
      </div>

      <div class="field">
        <br>
        <%= f.label :reagent, "Enter reagents" %>
        <br>
        <%= f.text_field :reagent, label: 'Reagent'%>
        <br>
        <small style="color: grey">⚠ Split reagents with space button and add new sample combination with / symbol</small>
        <br>
        <small style="color: grey">example: Sample-X Sample-Y / Sample-Z</small>
      </div>

      <div class="field">
        <br>
        <%= f.label :number_of_replication, "Enter number of replications" %>
        <br>
        <%= f.text_field :number_of_replication, label: 'Replicate' %>
        <br>
        <small style="color: grey">⚠ Split replicate numbers with comma (,)</small>
        <br>
        <small style="color: grey">example: 3,2</small>

      </div>
    </div>


    <br>
    <br>

    <%= link_to 'Home Page ',root_url, class: 'btn btn-dark' %>
    <%= f.button "Add Experiment", class: 'btn btn-primary', value: 'Create Experiment' %>
  <%  end %>
</div>


<style>
    #plate_size{
        font-size: 100px;
    }
</style>

app/views/generate_experiment_plates/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Experiment Plates</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<br>
<br>
<br>
<div class="row">
  <p id="notice"><%= notice %></p>
</div>

<br/>

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <% plate_quantity = @result.length %>
        <%@column_quantity = @result[0][0].length %>

        <% plate_quantity.times do |plate| %>
          <h1><%= return_plate_number(plate) %></h1>
          <table class="table table-bordered">
            <thead>
            <tr>
              <th scope="col"></th>
              <% @column_quantity.times do |column_number| %>
                <th scope="col"><%= return_columns(column_number) %></th>
              <% end %>
            </tr>
            </thead>
            <tbody>
            <% @row_quantity = @result[plate].length %>
            <% @row_quantity.times do |row_number| %>
              <tr>
                <th scope="row"><%= row_number + 1 %></th>
                <% @column_quantity.times do |column| %>
                  <th scope="row">
                    <%= fill_row_wells(plate, row_number, column) %>
                  </th>
                <% end %>
              </tr>
            <% end %>
            </tbody>
          </table>
          <br>
          <br>
        <% end %>
      </div>
    </div>
  </div>
</div>
</html>

app/views/layouts/_error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Experiment Denied</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="header-block">
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #1e4f9e !important">
    <strong><%= link_to 'Laboratory', root_url, class: 'navbar-brand text-family', style: 'color:white;margin-left: 10px'%></strong>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav" style="float: right !important;">
        <li class="nav-item position-absolute" style="bottom: 10px; right: 10px">
          <i class="bi bi-door-closed"><strong><%= link_to "Log Out", destroy_user_session_path, method: :delete %></strong></i>
        </li>
      </ul>
    </div>
  </nav>
</div>
<div class="container">
  <div class="alert alert-danger" role="alert" style="margin-top: 18%">
    <h4 class="alert-heading">Opps!</h4>
    <p>Unfortunately, plates for this experiment can't be generated because of its wrong data</p>
    <hr>
    <p class="mb-0">To generate experiments make sure that:</p>
    <br>
    <p>• Plate size is 96 or 384</p>
    <p>• Samples, Reagents and replication length is equal</p>
    <p>• Samples is not used in the same experiment multiple times</p>
    <p>• All reagents are unique</p>
  </div>
</div>
<div class="footer">
  <br>
  <small class="author">©Copyright: <a href="https://www.linkedin.com/in/sandro-shavdatuashvili-7b627b198/" target="_blank">Sandro Shavdatuashvili</a></small>
</div>
</body>
</html>

<style>
    .footer{
        width: 100%;
        height: 60px;
        background-color: #1e4f9e;
        color: white;
        text-decoration: none;
        position: fixed;
        bottom: 0;
    }
    a{
        color: white;
    }
    .author{
        margin-left: 43%;
    }
</style>

app/views/layouts/_page_not_found.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Laboratory - Page not found</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel ="icon" href="https://img.freepik.com/premium-vector/laboratory-icon-logo-vector-illustration-design-template_598213-1290.jpg?w=2000" type = "image/x-icon">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="header-block">
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #1e4f9e !important">
    <strong><%= link_to 'Laboratory', root_url, class: 'navbar-brand text-family', style: 'color:white;margin-left: 10px'%></strong>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav" style="float: right !important;">
        <li class="nav-item position-absolute" style="bottom: 10px; right: 10px">
          <i class="bi bi-door-closed"><strong><%= link_to "Log Out", destroy_user_session_path, method: :delete %></strong></i>
        </li>
      </ul>
    </div>
  </nav>
</div>
<div class="container">

</div>
<div class="footer">
  <br>
  <small class="author">©Copyright: <a href="https://www.linkedin.com/in/sandro-shavdatuashvili-7b627b198/" target="_blank">Sandro Shavdatuashvili</a></small>
</div>
</body>
</html>

<style>
    .footer{
        width: 100%;
        height: 60px;
        background-color: #1e4f9e;
        color: white;
        text-decoration: none;
        position: fixed;
        bottom: 0;
    }
    a{
        color: white;
    }
    .author{
        margin-left: 43%;
    }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Experiment Plate Generator - Home</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel ="icon" href="https://img.freepik.com/premium-vector/laboratory-icon-logo-vector-illustration-design-template_598213-1290.jpg?w=2000" type = "image/x-icon">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="header-block">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #1e4f9e !important">
      <strong><%= link_to 'Laboratory', root_url, class: 'navbar-brand text-family', style: 'color:white;margin-left: 10px'%></strong>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav" style="float: right !important;">
          <li class="nav-item position-absolute" style="bottom: 10px; right: 10px">
            <i class="bi bi-door-closed"><strong><%= link_to "Log Out", destroy_user_session_path, method: :delete %></strong></i>
          </li>
        </ul>
      </div>
    </nav>
  </div>
    <div class="container">
      <%= yield %>
    </div>
    <div class="footer">
      <br>
      <small class="author">©Copyright: <a href="https://www.linkedin.com/in/sandro-shavdatuashvili-7b627b198/" target="_blank">Sandro Shavdatuashvili</a></small>
    </div>
  </body>
</html>

<style>
    .footer{
        width: 100%;
        height: 60px;
        background-color: #1e4f9e;
        color: white;
        text-decoration: none;
        position: fixed;
        bottom: 0;
    }
    a{
        color: white;
    }
    .author{
        margin-left: 43%;
    }
</style>